#!/bin/sh

rm -rf autom4te.cache
rm -f config.log config.status configure 
rm -f `find . -name Makefile.in`
rm -f `find . -name Makefile | grep -v examples`
rm -f `find . -name .dirstamp`
rm -f inc/config.h
rm -f inc/stamp-h1
rm -f aclocal.m4 
rm -f config/install-sh
rm -f config/missing
rm -f config/compile
rm -f config/config.guess
rm -f config/config.sub
rm -f .msg

