#define C8  (8+1)
#define C16 (C8 * 2)
#define int32 int

#define SAC_HEADER_V6                           \
    X(delta,    DELTA,       float)             \
    X(depmin,   DEPMIN,      float)             \
    X(depmax,   DEPMAX,      float)             \
    X(scale,    SCALE,       float)             \
    X(odelta,   ODELTA,      float)             \
    X(b,        B,           float)             \
    X(e,        E,           float)             \
    X(o,        O,           float)             \
    X(a,        A,           float)             \
    X(fmt,      FMT,         float)             \
    X(t0,       T0,          float)             \
    X(t1,       T1,          float)             \
    X(t2,       T2,          float)             \
    X(t3,       T3,          float)             \
    X(t4,       T4,          float)             \
    X(t5,       T5,          float)             \
    X(t6,       T6,          float)             \
    X(t7,       T7,          float)             \
    X(t8,       T8,          float)             \
    X(t9,       T9,          float)             \
    X(f,        F,           float)             \
    X(resp0,    RESP0,       float)             \
    X(resp1,    RESP1,       float)             \
    X(resp2,    RESP2,       float)             \
    X(resp3,    RESP3,       float)             \
    X(resp4,    RESP4,       float)             \
    X(resp5,    RESP5,       float)             \
    X(resp6,    RESP6,       float)             \
    X(resp7,    RESP7,       float)             \
    X(resp8,    RESP8,       float)             \
    X(resp9,    RESP9,       float)             \
    X(stla,     STLA,        float)             \
    X(stlo,     STLO,        float)             \
    X(stel,     STEL,        float)             \
    X(stdp,     STDP,        float)             \
    X(evla,     EVLA,        float)             \
    X(evlo,     EVLO,        float)             \
    X(evel,     EVEL,        float)             \
    X(evdp,     EVDP,        float)             \
    X(mag,      MAG,         float)             \
    X(user0,    USER0,       float)             \
    X(user1,    USER1,       float)             \
    X(user2,    USER2,       float)             \
    X(user3,    USER3,       float)             \
    X(user4,    USER4,       float)             \
    X(user5,    USER5,       float)             \
    X(user6,    USER6,       float)             \
    X(user7,    USER7,       float)             \
    X(user8,    USER8,       float)             \
    X(user9,    USER9,       float)             \
    X(dist,     DIST,        float)             \
    X(az,       AZ,          float)             \
    X(baz,      BAZ,         float)             \
    X(gcarc,    GCARC,       float)             \
    X(sb,       SAVED_B,     float)             \
    X(sdelta,   SAVED_DELTA, float)             \
    X(depmen,   DEPMEN,      float)             \
    X(cmpaz,    CMPAZ,       float)             \
    X(cmpinc,   CMPINC,      float)             \
    X(xminimum, XMINIMUM,    float)             \
    X(xmaximum, XMAXIMUM,    float)             \
    X(yminimum, YMINIMUM,    float)             \
    X(ymaximum, YMAXIMUM,    float)             \
    X(unused6,  UNUSED6,     float)             \
    X(unused7,  UNUSED7,     float)             \
    X(unused8,  UNUSED8,     float)             \
    X(unused9,  UNUSED9,     float)             \
    X(unused10, UNUSED10,    float)             \
    X(unused11, UNUSED11,    float)             \
    X(unused12, UNUSED12,    float)             \
    X(nzyear,   NZYEAR,      int32)           \
    X(nzjday,   NZJDAY,      int32)           \
    X(nzhour,   NZHOUR,      int32)           \
    X(nzmin,    NZMIN,       int32)           \
    X(nzsec,    NZSEC,       int32)           \
    X(nzmsec,   NZMSEC,      int32)           \
    X(nvhdr,    NVHDR,       int32)           \
    X(norid,    NORID,       int32)           \
    X(nevid,    NEVID,       int32)           \
    X(npts,     NPTS,        int32)           \
    X(nsnpts,   SAVE_NPTS,   int32)           \
    X(nwfid,    NWFID,       int32)           \
    X(nxsize,   NXSIZE,      int32)           \
    X(nysize,   NYSIZE,      int32)           \
    X(unused15, UNUSED15,    int32)           \
    X(iftype,   IFTYPE,      int32)           \
    X(idep,     IDEP,        int32)           \
    X(iztype,   IZTYPE,      int32)           \
    X(unused16, UNUSED16,    int32)           \
    X(iinst,    IINST,       int32)           \
    X(istreg,   ISTREG,      int32)           \
    X(ievreg,   IEVREG,      int32)           \
    X(ievtyp,   IEVTYP,      int32)           \
    X(iqual,    IQUAL,       int32)           \
    X(isynth,   ISYNTH,      int32)           \
    X(imagtyp,  IMAGTYP,     int32)           \
    X(imagsrc,  IMAGSRC,     int32)           \
    X(unused19, UNUSED19,    int32)           \
    X(unused20, UNUSED20,    int32)           \
    X(unused21, UNUSED21,    int32)           \
    X(unused22, UNUSED22,    int32)           \
    X(unused23, UNUSED23,    int32)           \
    X(unused24, UNUSED24,    int32)           \
    X(unused25, UNUSED25,    int32)           \
    X(unused26, UNUSED26,    int32)           \
    X(leven,    LEVEN,       int32)           \
    X(lpspol,   LPSPOL,      int32)           \
    X(lovrok,   LOVROK,      int32)           \
    X(lcalda,   LCALDA,      int32)           \
    X(unused27, UNUSED27,    int32)           \
    X(kstnm[C8],    KSTNM,   char)            \
    X(kevnm[C16],    KEVNM,  char)            \
    X(khole[C8],    KHOLE,   char)            \
    X(ko[C8],       KO,      char)            \
    X(ka[C8],       KA,      char)            \
    X(kt0[C8],      KT0,     char)            \
    X(kt1[C8],      KT1,     char)            \
    X(kt2[C8],      KT2,     char)            \
    X(kt3[C8],      KT3,     char)            \
    X(kt4[C8],      KT4,     char)            \
    X(kt5[C8],      KT5,     char)            \
    X(kt6[C8],      KT6,     char)            \
    X(kt7[C8],      KT7,     char)            \
    X(kt8[C8],      KT8,     char)            \
    X(kt9[C8],      KT9,     char)            \
    X(kf[C8],       KF,      char)            \
    X(kuser0[C8],   KUSER0,  char)            \
    X(kuser1[C8],   KUSER1,  char)            \
    X(kuser2[C8],   KUSER2,  char)            \
    X(kcmpnm[C8],   KCMPNM,  char)            \
    X(knetwk[C8],   KNETWK,  char)            \
    X(kdatrd[C8],   KDATRD,  char)            \
    X(kinst[C8],    KINST,   char)
