void iniam();
void khdr();
void sac_alloc();
void sac_buffer_free();
void sac_buffer_new();
void sac_comps();
void sac_copy();
void sac_data_copy();
void sac_data_exists();
void sac_extrema();
void sac_find_filename();
void sac_free();
void sac_hdr_init();
void sac_hdr_new();
void sac_header_copy();
void sac_meta_copy();
void sac_meta_new();
void sac_new();
void sacclear();
void sacdel();
void sacget();
void sacget_current();
void sacget_current_id();
void saclen();
void sacpop();
void sacpop_no_free();
void sacput();
void sacsort();
void xarray_append();
void xarray_clear();
void xarray_delete();
void xarray_free();
void xarray_grow();
void xarray_header();
void xarray_length();
void xarray_new();
void xarray_new_with_len();
void xarray_pop();
void xarray_sort();
void getbb();
void getbbv();
void getbbv_();
void getbbv__();
void inibbs();
void setbb();
void setbbv();
void setbbv_();
void setbbv__();
void unsetbbv();
void unsetbbv_();
void unsetbbv__();
void writebbf();
void writebbf_();
void writebbf__();
void readbbf();
void readbbf_();
void readbbf__();
void crname();
void indexa();
void indexb();
void lstrip();
void rstrip();
void strcut();
void modcase();
void nequal();
void fstrncpy();
void ipow();
void isign();
void powi();
void sign();
void subscpy();
void sacaux();
void zbasename();
void zclose();
void zclosec();
void zcloses();
void zdest();
void zgetc();
void zinquire();
void znfile();
void znfilef();
void znfilef_();
void znfilef__();
void zopen_sac();
void zopenc();
void zopenc_();
void zopenc__();
void zopens();
void zputc();
void zrabs();
void zsysop();
void zsysop_gets();
void zwabs();
void getfhv();
void getfhv_();
void getfhv__();
void sacio_char_to_keyword();
void sacio_message();
void sacio_message_control();
void getihv();
void getihv_();
void getihv__();
void getihv_internal();
void getkhv();
void getkhv_();
void getkhv__();
void getkhv_internal();
void hdr_len();
void is_kundef();
void is_kundef2();
void is_kundefn();
void getlhv();
void getlhv_();
void getlhv__();
void getnhv();
void getnhv_();
void getnhv__();
void inihdr();
void inihdr_();
void inihdr__();
void inilhf();
void map_chdr_in();
void map_chdr_out();
void newhdr();
void newhdr_();
void newhdr__();
void rsac1();
void rsac1_();
void rsac1__();
void sac_data_read();
void sac_data_read_new();
void sac_data_swap();
void sac_header_read_new();
void sac_read();
void sac_read_header();
void sac_read_internal();
void rsac2();
void rsac2_();
void rsac2__();
void setfhv();
void setfhv_();
void setfhv__();
void setihv();
void setihv_();
void setihv__();
void setkhv();
void setkhv_();
void setkhv__();
void setlhv();
void setlhv_();
void setlhv__();
void setnhv();
void setnhv_();
void setnhv__();
void CheckByteOrder();
void sac_byte_order();
void sac_check_lovrok();
void sac_check_npts();
void sac_data_write();
void sac_data_write1();
void sac_data_write2();
void sac_header_write();
void sac_write();
void sac_write_internal();
void sac_write_r();
void wsac0();
void wsac0_();
void wsac0__();
void wsac1();
void wsac1_();
void wsac1__();
void wsac2();
void wsac2_();
void wsac2__();
void DEPRECATED();
void fstrdup();
void fstrset();
void fstrtrim();
void update_distaz();
void wsac3();
void wsac3_();
void wsac3__();
void rsach();
void sac_check_header_version();
void sac_header_read();
void sac_header_swap();
void sacio_initialize_common();
void hdrfld();
void hdrfldf();
void hdrfldf_();
void hdrfldf__();
void apcmsg();
void apcmsg2();
void apcmsgnum();
void apimsg();
void aplmsg();
void clrmsg();
void getsmsg();
void check_message_subsystem();
void encode_error();
void error();
void error_occurred();
void error_status();
void getsmsg2();
void inimsg();
void message();
void mprint();
void msg();
void out();
void processed();
void sac_error_control();
void sac_error_off();
void sac_error_off_();
void sac_error_off__();
void sac_error_stderr();
void sac_error_stderr_();
void sac_error_stderr__();
void sac_error_stdout();
void sac_error_stdout_();
void sac_error_stdout__();
void sac_message_control();
void sac_msg_add();
void sac_output_off();
void sac_output_off_();
void sac_output_off__();
void sac_output_stderr();
void sac_output_stderr_();
void sac_output_stderr__();
void sac_output_stdout();
void sac_output_stdout_();
void sac_output_stdout__();
void sac_warning_control();
void sac_warning_off();
void sac_warning_off_();
void sac_warning_off__();
void sac_warning_stderr();
void sac_warning_stderr_();
void sac_warning_stderr__();
void sac_warning_stdout();
void sac_warning_stdout_();
void sac_warning_stdout__();
void warning();
void sacmsg();
void sendmesg();
void setmsg();
void typmsg();
void wrtmsg();
void apfmsg();
void bell();
void bell_off();
void bell_on();
void outmsg();
void byteswap();
void cnvita();
void fill();
void ljust();
void dsum();
void extrma();
void fsum();
void kahan_sum();
void distaz();
void createvlist();
void deletev();
void deletevlist();
void getvFILEptr();
void getvvstring();
void getvvstringZ();
void token_to_line();
void upcase_dup();
void initializevars();
void inivars();
void vfilelist_free();
void putvFILEptr();
void putvvstring();
void readvfile();
void writevfile();
void bbf_to_sacvar();
void dict_free_var();
void len4();
void sac_vars_create();
void sac_vars_delete();
void sac_vars_delete_var();
void sac_vars_exists();
void sac_vars_free();
void sac_vars_get();
void sac_vars_get_int();
void sac_vars_get_internal();
void sac_vars_get_string();
void sac_vars_get_value();
void sac_vars_get_var();
void sac_vars_init();
void sac_vars_keys();
void sac_vars_put_var();
void sac_vars_read();
void sac_vars_to_bbf();
void sac_vars_write();
void setvar();
void setvar_ap();
void var_alloc();
void var_free();
void var_init();
void var_new();
void var_new_int();
void var_new_internal();
void var_new_list();
void var_new_string();
void var_new_value();
void dict_entry_alloc();
void dict_free();
void dict_get();
void dict_get_internal();
void dict_keys();
void dict_new();
void dict_new_with_length();
void dict_put();
void dict_remove();
void dict_resize();
void dict_resize_limit();
void dict_status();
void hash();
void prime_larger();
void bbf_error();
void bbf_free();
void bbf_message();
void bbf_new();
void bbf_read();
void bbf_set_header();
void bbf_set_library_use();
void bbf_set_var();
void bbf_verbose();
void bbf_write();
void decodeHeader();
void dumpHeader();
void encodeHeader();
void int2bin();
void swap();
void debug();
void fgetsp();
void read_chars();
void sscanff();
void strchr_reverse();
void strchr_reverse_isnot();
void string_alloc();
void string_append();
void string_append_int();
void string_check();
void string_check_length();
void string_compare();
void string_compare_v();
void string_compare_v_inv();
void string_copy();
void string_count();
void string_dump();
void string_dump_v();
void string_equal();
void string_equal_char();
void string_free();
void string_free_v();
void string_from_fortran();
void string_grow();
void string_insert();
void string_length();
void string_nalloc();
void string_new();
void string_pack();
void string_prepend();
void string_prepend_int();
void string_printf();
void string_printf_append();
void string_printf_append_internal();
void string_printf_prepend();
void string_printf_prepend_internal();
void string_remove();
void string_replace();
void string_string();
void string_substr();
void string_substr_char();
void string_trunc();
void strstr_escape();
void datetime_add_hms();
void datetime_alloc();
void datetime_atoi();
void datetime_atol();
void datetime_compare();
void datetime_copy();
void datetime_copy_deep();
void datetime_day_of_the_week();
void datetime_doy2ymd();
void datetime_free();
void datetime_in_span();
void datetime_init();
void datetime_merge();
void datetime_new();
void datetime_normalize();
void datetime_normalize_ymd();
void datetime_parse();
void datetime_print();
void datetime_print_date();
void datetime_printn();
void datetime_printn_date();
void datetime_set_day();
void datetime_set_doy();
void datetime_set_hour();
void datetime_set_minute();
void datetime_set_month();
void datetime_set_nanosecond();
void datetime_set_second();
void datetime_set_year();
void datetime_status();
void datetime_status_message();
void datetime_string();
void datetime_strptime();
void datetime_ymd2doy();
void day_of_the_week();
void doy();
void norm();
void year();
void not_used(int v);
int main() {
   not_used(0);
   return 0;
}
void
not_used(int v) {
   if (v == 0) {
       return;
   }
     iniam();
     khdr();
     sac_alloc();
     sac_buffer_free();
     sac_buffer_new();
     sac_comps();
     sac_copy();
     sac_data_copy();
     sac_data_exists();
     sac_extrema();
     sac_find_filename();
     sac_free();
     sac_hdr_init();
     sac_hdr_new();
     sac_header_copy();
     sac_meta_copy();
     sac_meta_new();
     sac_new();
     sacclear();
     sacdel();
     sacget();
     sacget_current();
     sacget_current_id();
     saclen();
     sacpop();
     sacpop_no_free();
     sacput();
     sacsort();
     xarray_append();
     xarray_clear();
     xarray_delete();
     xarray_free();
     xarray_grow();
     xarray_header();
     xarray_length();
     xarray_new();
     xarray_new_with_len();
     xarray_pop();
     xarray_sort();
     getbb();
     getbbv();
     getbbv_();
     getbbv__();
     inibbs();
     setbb();
     setbbv();
     setbbv_();
     setbbv__();
     unsetbbv();
     unsetbbv_();
     unsetbbv__();
     writebbf();
     writebbf_();
     writebbf__();
     readbbf();
     readbbf_();
     readbbf__();
     crname();
     indexa();
     indexb();
     lstrip();
     rstrip();
     strcut();
     modcase();
     nequal();
     fstrncpy();
     ipow();
     isign();
     powi();
     sign();
     subscpy();
     sacaux();
     zbasename();
     zclose();
     zclosec();
     zcloses();
     zdest();
     zgetc();
     zinquire();
     znfile();
     znfilef();
     znfilef_();
     znfilef__();
     zopen_sac();
     zopenc();
     zopenc_();
     zopenc__();
     zopens();
     zputc();
     zrabs();
     zsysop();
     zsysop_gets();
     zwabs();
     getfhv();
     getfhv_();
     getfhv__();
     sacio_char_to_keyword();
     sacio_message();
     sacio_message_control();
     getihv();
     getihv_();
     getihv__();
     getihv_internal();
     getkhv();
     getkhv_();
     getkhv__();
     getkhv_internal();
     hdr_len();
     is_kundef();
     is_kundef2();
     is_kundefn();
     getlhv();
     getlhv_();
     getlhv__();
     getnhv();
     getnhv_();
     getnhv__();
     inihdr();
     inihdr_();
     inihdr__();
     inilhf();
     map_chdr_in();
     map_chdr_out();
     newhdr();
     newhdr_();
     newhdr__();
     rsac1();
     rsac1_();
     rsac1__();
     sac_data_read();
     sac_data_read_new();
     sac_data_swap();
     sac_header_read_new();
     sac_read();
     sac_read_header();
     sac_read_internal();
     rsac2();
     rsac2_();
     rsac2__();
     setfhv();
     setfhv_();
     setfhv__();
     setihv();
     setihv_();
     setihv__();
     setkhv();
     setkhv_();
     setkhv__();
     setlhv();
     setlhv_();
     setlhv__();
     setnhv();
     setnhv_();
     setnhv__();
     CheckByteOrder();
     sac_byte_order();
     sac_check_lovrok();
     sac_check_npts();
     sac_data_write();
     sac_data_write1();
     sac_data_write2();
     sac_header_write();
     sac_write();
     sac_write_internal();
     sac_write_r();
     wsac0();
     wsac0_();
     wsac0__();
     wsac1();
     wsac1_();
     wsac1__();
     wsac2();
     wsac2_();
     wsac2__();
     DEPRECATED();
     fstrdup();
     fstrset();
     fstrtrim();
     update_distaz();
     wsac3();
     wsac3_();
     wsac3__();
     rsach();
     sac_check_header_version();
     sac_header_read();
     sac_header_swap();
     sacio_initialize_common();
     hdrfld();
     hdrfldf();
     hdrfldf_();
     hdrfldf__();
     apcmsg();
     apcmsg2();
     apcmsgnum();
     apimsg();
     aplmsg();
     clrmsg();
     getsmsg();
     check_message_subsystem();
     encode_error();
     error();
     error_occurred();
     error_status();
     getsmsg2();
     inimsg();
     message();
     mprint();
     msg();
     out();
     processed();
     sac_error_control();
     sac_error_off();
     sac_error_off_();
     sac_error_off__();
     sac_error_stderr();
     sac_error_stderr_();
     sac_error_stderr__();
     sac_error_stdout();
     sac_error_stdout_();
     sac_error_stdout__();
     sac_message_control();
     sac_msg_add();
     sac_output_off();
     sac_output_off_();
     sac_output_off__();
     sac_output_stderr();
     sac_output_stderr_();
     sac_output_stderr__();
     sac_output_stdout();
     sac_output_stdout_();
     sac_output_stdout__();
     sac_warning_control();
     sac_warning_off();
     sac_warning_off_();
     sac_warning_off__();
     sac_warning_stderr();
     sac_warning_stderr_();
     sac_warning_stderr__();
     sac_warning_stdout();
     sac_warning_stdout_();
     sac_warning_stdout__();
     warning();
     sacmsg();
     sendmesg();
     setmsg();
     typmsg();
     wrtmsg();
     apfmsg();
     bell();
     bell_off();
     bell_on();
     outmsg();
     byteswap();
     cnvita();
     fill();
     ljust();
     dsum();
     extrma();
     fsum();
     kahan_sum();
     distaz();
     createvlist();
     deletev();
     deletevlist();
     getvFILEptr();
     getvvstring();
     getvvstringZ();
     token_to_line();
     upcase_dup();
     initializevars();
     inivars();
     vfilelist_free();
     putvFILEptr();
     putvvstring();
     readvfile();
     writevfile();
     bbf_to_sacvar();
     dict_free_var();
     len4();
     sac_vars_create();
     sac_vars_delete();
     sac_vars_delete_var();
     sac_vars_exists();
     sac_vars_free();
     sac_vars_get();
     sac_vars_get_int();
     sac_vars_get_internal();
     sac_vars_get_string();
     sac_vars_get_value();
     sac_vars_get_var();
     sac_vars_init();
     sac_vars_keys();
     sac_vars_put_var();
     sac_vars_read();
     sac_vars_to_bbf();
     sac_vars_write();
     setvar();
     setvar_ap();
     var_alloc();
     var_free();
     var_init();
     var_new();
     var_new_int();
     var_new_internal();
     var_new_list();
     var_new_string();
     var_new_value();
     dict_entry_alloc();
     dict_free();
     dict_get();
     dict_get_internal();
     dict_keys();
     dict_new();
     dict_new_with_length();
     dict_put();
     dict_remove();
     dict_resize();
     dict_resize_limit();
     dict_status();
     hash();
     prime_larger();
     bbf_error();
     bbf_free();
     bbf_message();
     bbf_new();
     bbf_read();
     bbf_set_header();
     bbf_set_library_use();
     bbf_set_var();
     bbf_verbose();
     bbf_write();
     decodeHeader();
     dumpHeader();
     encodeHeader();
     int2bin();
     swap();
     debug();
     fgetsp();
     read_chars();
     sscanff();
     strchr_reverse();
     strchr_reverse_isnot();
     string_alloc();
     string_append();
     string_append_int();
     string_check();
     string_check_length();
     string_compare();
     string_compare_v();
     string_compare_v_inv();
     string_copy();
     string_count();
     string_dump();
     string_dump_v();
     string_equal();
     string_equal_char();
     string_free();
     string_free_v();
     string_from_fortran();
     string_grow();
     string_insert();
     string_length();
     string_nalloc();
     string_new();
     string_pack();
     string_prepend();
     string_prepend_int();
     string_printf();
     string_printf_append();
     string_printf_append_internal();
     string_printf_prepend();
     string_printf_prepend_internal();
     string_remove();
     string_replace();
     string_string();
     string_substr();
     string_substr_char();
     string_trunc();
     strstr_escape();
     datetime_add_hms();
     datetime_alloc();
     datetime_atoi();
     datetime_atol();
     datetime_compare();
     datetime_copy();
     datetime_copy_deep();
     datetime_day_of_the_week();
     datetime_doy2ymd();
     datetime_free();
     datetime_in_span();
     datetime_init();
     datetime_merge();
     datetime_new();
     datetime_normalize();
     datetime_normalize_ymd();
     datetime_parse();
     datetime_print();
     datetime_print_date();
     datetime_printn();
     datetime_printn_date();
     datetime_set_day();
     datetime_set_doy();
     datetime_set_hour();
     datetime_set_minute();
     datetime_set_month();
     datetime_set_nanosecond();
     datetime_set_second();
     datetime_set_year();
     datetime_status();
     datetime_status_message();
     datetime_string();
     datetime_strptime();
     datetime_ymd2doy();
     day_of_the_week();
     doy();
     norm();
     year();
}
