
int not_used(int v);

int
main() {
    not_used(0);
    return 0;
}

int    getbbv();
int    getbbv_();
int    getbbv__();

int    setbbv();
int    setbbv_();
int    setbbv__();

int    unsetbbv();
int    unsetbbv_();
int    unsetbbv__();

int    writebbf();
int    writebbf_();
int    writebbf__();

int    readbbf();
int    readbbf_();
int    readbbf__();

int    znfile();
int    znfilef();
int    znfilef_();
int    znfilef__();

int    zopenc();
int    zopenc_();
int    zopenc__();

int    getfhv();
int    getfhv_();
int    getfhv__();

int    getihv();
int    getihv_();
int    getihv__();

int    getkhv();
int    getkhv_();
int    getkhv__();

int    getlhv();
int    getlhv_();
int    getlhv__();
int    getnhv();
int    getnhv_();
int    getnhv__();
int    inihdr();
int    inihdr_();
int    inihdr__();

int    newhdr();
int    newhdr_();
int    newhdr__();
int    rsac1();
int    rsac1_();
int    rsac1__();
int    rsac2();
int    rsac2_();
int    rsac2__();
int    setfhv();
int    setfhv_();
int    setfhv__();
int    setihv();
int    setihv_();
int    setihv__();
int    setkhv();
int    setkhv_();
int    setkhv__();
int    setlhv();
int    setlhv_();
int    setlhv__();
int    setnhv();
int    setnhv_();
int    setnhv__();
int    wsac0();
int    wsac0_();
int    wsac0__();
int    wsac1();
int    wsac1_();
int    wsac1__();
int    wsac2();
int    wsac2_();
int    wsac2__();
int    wsac3();
int    wsac3_();
int    wsac3__();
int    hdrfld();
int    hdrfldf();
int    hdrfldf_();
int    hdrfldf__();
int    sac_error_off();
int    sac_error_off_();
int    sac_error_off__();
int    sac_error_stderr();
int    sac_error_stderr_();
int    sac_error_stderr__();
int    sac_error_stdout();
int    sac_error_stdout_();
int    sac_error_stdout__();
int    sac_output_off();
int    sac_output_off_();
int    sac_output_off__();
int    sac_output_stderr();
int    sac_output_stderr_();
int    sac_output_stderr__();
int    sac_output_stdout();
int    sac_output_stdout_();
int    sac_output_stdout__();
int    sac_warning_off();
int    sac_warning_off_();
int    sac_warning_off__();
int    sac_warning_stderr();
int    sac_warning_stderr_();
int    sac_warning_stderr__();
int    sac_warning_stdout();
int    sac_warning_stdout_();
int    sac_warning_stdout__();

/* Not Real Function */
int    not_a_function_here();

/* Internal Functions */
int    iniam();
int    khdr();
int    sac_alloc();
int    sac_buffer_free();
int    sac_buffer_new();
int    sac_comps();
int    sac_copy();
int    sac_data_copy();
int    sac_data_exists();
int    sac_extrema();
int    sac_find_filename();
int    sac_free();
int    sac_hdr_init();
int    sac_hdr_new();
int    sac_header_copy();
int    sac_meta_copy();
int    sac_meta_new();
int    sac_new();
int    sacclear();
int    sacdel();
int    sacget();
int    sacget_current();
int    sacget_current_id();
int    saclen();
int    sacpop();
int    sacpop_no_free();
int    sacput();
int    sacsort();
int    xarray_append();
int    xarray_clear();
int    xarray_delete();
int    xarray_free();
int    xarray_grow();
int    xarray_header();
int    xarray_length();
int    xarray_new();
int    xarray_new_with_len();
int    xarray_pop();
int    xarray_sort();
int    inibbs();
int    crname();
int    indexa();
int    indexb();
int    lstrip();
int    rstrip();
int    strcut();
int    modcase();
int    nequal();
int    fstrncpy();
int    ipow();
int    isign();
int    powi();
int    sign();
int    subscpy();
int    sacaux();
int    zbasename();
int    zclose();
int    zclosec();
int    zcloses();
int    zdest();
int    zgetc();
int    zinquire();
int    zopen_sac();
int    zopens();
int    zputc();
int    zrabs();
int    zsysop();
int    zsysop_gets();
int    zwabs();
int    sacio_char_to_keyword();
int    sacio_message();
int    sacio_message_control();
int    getihv_internal();
int    getkhv_internal();
int    hdr_len();
int    is_kundef();
int    is_kundef2();
int    is_kundefn();
int    inilhf();
int    map_chdr_in();
int    map_chdr_out();
int    sac_data_read();
int    sac_data_read_new();
int    sac_data_swap();
int    sac_header_read_new();
int    sac_read();
int    sac_read_header();
int    sac_read_internal();
int    CheckByteOrder();
int    sac_byte_order();
int    sac_check_lovrok();
int    sac_check_npts();
int    sac_data_write();
int    sac_data_write1();
int    sac_data_write2();
int    sac_header_write();
int    sac_write();
int    sac_write_internal();
int    sac_write_r();
int    DEPRECATED();
int    fstrdup();
int    fstrset();
int    fstrtrim();
int    update_distaz();
int    rsach();
int    sac_check_header_version();
int    sac_header_read();
int    sac_header_swap();
int    sacio_initialize_common();
int    apcmsg();
int    apcmsg2();
int    apcmsgnum();
int    apimsg();
int    aplmsg();
int    clrmsg();
int    getsmsg();
int    check_message_subsystem();
int    encode_error();
int    error();
int    error_occurred();
int    error_status();
int    getsmsg2();
int    inimsg();
int    message();
int    mprint();
int    msg();
int    out();
int    processed();
int    sac_error_control();
int    sac_message_control();
int    sac_msg_add();
int    sac_warning_control();
int    warning();
int    sacmsg();
int    sendmesg();
int    setmsg();
int    typmsg();
int    wrtmsg();
int    apfmsg();
int    bell();
int    bell_off();
int    bell_on();
int    outmsg();
int    byteswap();
int    cnvita();
int    fill();
int    ljust();
int    dsum();
int    extrma();
int    fsum();
int    kahan_sum();
int    distaz();
int    createvlist();
int    deletev();
int    deletevlist();
int    getvFILEptr();
int    getvvstring();
int    getvvstringZ();
int    token_to_line();
int    upcase_dup();
int    initializevars();
int    inivars();
int    vfilelist_free();
int    putvFILEptr();
int    putvvstring();
int    readvfile();
int    writevfile();
int    bbf_to_sacvar();
int    dict_free_var();
int    len4();
int    sac_vars_create();
int    sac_vars_delete();
int    sac_vars_delete_var();
int    sac_vars_exists();
int    sac_vars_free();
int    sac_vars_get();
int    sac_vars_get_int();
int    sac_vars_get_internal();
int    sac_vars_get_string();
int    sac_vars_get_value();
int    sac_vars_get_var();
int    sac_vars_init();
int    sac_vars_keys();
int    sac_vars_put_var();
int    sac_vars_read();
int    sac_vars_to_bbf();
int    sac_vars_write();
int    setvar();
int    setvar_ap();
int    var_alloc();
int    var_free();
int    var_init();
int    var_new();
int    var_new_int();
int    var_new_internal();
int    var_new_list();
int    var_new_string();
int    var_new_value();
int    dict_entry_alloc();
int    dict_free();
int    dict_get();
int    dict_get_internal();
int    dict_keys();
int    dict_new();
int    dict_new_with_length();
int    dict_put();
int    dict_remove();
int    dict_resize();
int    dict_resize_limit();
int    dict_status();
int    hash();
int    prime_larger();
int    bbf_error();
int    bbf_free();
int    bbf_message();
int    bbf_new();
int    bbf_read();
int    bbf_set_header();
int    bbf_set_library_use();
int    bbf_set_var();
int    bbf_verbose();
int    bbf_write();
int    decodeHeader();
int    dumpHeader();
int    encodeHeader();
int    int2bin();
int    swap();
int    debug();
int    fgetsp();
int    read_chars();
int    sscanff();
int    strchr_reverse();
int    strchr_reverse_isnot();
int    string_alloc();
int    string_append();
int    string_append_int();
int    string_check();
int    string_check_length();
int    string_compare();
int    string_compare_v();
int    string_compare_v_inv();
int    string_copy();
int    string_count();
int    string_dump();
int    string_dump_v();
int    string_equal();
int    string_equal_char();
int    string_free();
int    string_free_v();
int    string_from_fortran();
int    string_grow();
int    string_insert();
int    string_length();
int    string_nalloc();
int    string_new();
int    string_pack();
int    string_prepend();
int    string_prepend_int();
int    string_printf();
int    string_printf_append();
int    string_printf_append_internal();
int    string_printf_prepend();
int    string_printf_prepend_internal();
int    string_remove();
int    string_replace();
int    string_string();
int    string_substr();
int    string_substr_char();
int    string_trunc();
int    strstr_escape();
int    datetime_add_hms();
int    datetime_alloc();
int    datetime_atoi();
int    datetime_atol();
int    datetime_compare();
int    datetime_copy();
int    datetime_copy_deep();
int    datetime_day_of_the_week();
int    datetime_doy2ymd();
int    datetime_free();
int    datetime_in_span();
int    datetime_init();
int    datetime_merge();
int    datetime_new();
int    datetime_normalize();
int    datetime_normalize_ymd();
int    datetime_parse();
int    datetime_print();
int    datetime_print_date();
int    datetime_printn();
int    datetime_printn_date();
int    datetime_set_day();
int    datetime_set_doy();
int    datetime_set_hour();
int    datetime_set_minute();
int    datetime_set_month();
int    datetime_set_nanosecond();
int    datetime_set_second();
int    datetime_set_year();
int    datetime_status();
int    datetime_status_message();
int    datetime_string();
int    datetime_strptime();
int    datetime_ymd2doy();
int    day_of_the_week();
int    doy();
int    norm();
int    year();


int
not_used (int v) {
    if (v == 0) {
        return 0;
    }
        /* API */
   getbbv();
   getbbv_();
   getbbv__();

   setbbv();
   setbbv_();
   setbbv__();

   unsetbbv();
   unsetbbv_();
   unsetbbv__();

   writebbf();
   writebbf_();
   writebbf__();

   readbbf();
   readbbf_();
   readbbf__();

   znfile();
   znfilef();
   znfilef_();
   znfilef__();

   zopenc();
   zopenc_();
   zopenc__();

   getfhv();
   getfhv_();
   getfhv__();

   getihv();
   getihv_();
   getihv__();

   getkhv();
   getkhv_();
   getkhv__();

   getlhv();
   getlhv_();
   getlhv__();
   getnhv();
   getnhv_();
   getnhv__();
   inihdr();
   inihdr_();
   inihdr__();

   newhdr();
   newhdr_();
   newhdr__();
   rsac1();
   rsac1_();
   rsac1__();
   rsac2();
   rsac2_();
   rsac2__();
   setfhv();
   setfhv_();
   setfhv__();
   setihv();
   setihv_();
   setihv__();
   setkhv();
   setkhv_();
   setkhv__();
   setlhv();
   setlhv_();
   setlhv__();
   setnhv();
   setnhv_();
   setnhv__();
   wsac0();
   wsac0_();
   wsac0__();
   wsac1();
   wsac1_();
   wsac1__();
   wsac2();
   wsac2_();
   wsac2__();
   wsac3();
   wsac3_();
   wsac3__();
   hdrfld();
   hdrfldf();
   hdrfldf_();
   hdrfldf__();
   sac_error_off();
   sac_error_off_();
   sac_error_off__();
   sac_error_stderr();
   sac_error_stderr_();
   sac_error_stderr__();
   sac_error_stdout();
   sac_error_stdout_();
   sac_error_stdout__();
   sac_output_off();
   sac_output_off_();
   sac_output_off__();
   sac_output_stderr();
   sac_output_stderr_();
   sac_output_stderr__();
   sac_output_stdout();
   sac_output_stdout_();
   sac_output_stdout__();
   sac_warning_off();
   sac_warning_off_();
   sac_warning_off__();
   sac_warning_stderr();
   sac_warning_stderr_();
   sac_warning_stderr__();
   sac_warning_stdout();
   sac_warning_stdout_();
   sac_warning_stdout__();

   /* Not Real Function */
   //not_a_function_here();

   /* Internal Functions */
   iniam();
   khdr();
   sac_alloc();
   sac_buffer_free();
   sac_buffer_new();
   sac_comps();
   sac_copy();
   sac_data_copy();
   sac_data_exists();
   sac_extrema();
   sac_find_filename();
   sac_free();
   sac_hdr_init();
   sac_hdr_new();
   sac_header_copy();
   sac_meta_copy();
   sac_meta_new();
   sac_new();
   sacclear();
   sacdel();
   sacget();
   sacget_current();
   sacget_current_id();
   saclen();
   sacpop();
   sacpop_no_free();
   sacput();
   sacsort();
   xarray_append();
   xarray_clear();
   xarray_delete();
   xarray_free();
   xarray_grow();
   xarray_header();
   xarray_length();
   xarray_new();
   xarray_new_with_len();
   xarray_pop();
   xarray_sort();
   inibbs();
   crname();
   indexa();
   indexb();
   lstrip();
   rstrip();
   strcut();
   modcase();
   nequal();
   fstrncpy();
   ipow();
   isign();
   powi();
   sign();
   subscpy();
   sacaux();
   zbasename();
   zclose();
   zclosec();
   zcloses();
   zdest();
   zgetc();
   zinquire();
   zopen_sac();
   zopens();
   zputc();
   zrabs();
   zsysop();
   zsysop_gets();
   zwabs();
   sacio_char_to_keyword();
   sacio_message();
   sacio_message_control();
   getihv_internal();
   getkhv_internal();
   hdr_len();
   is_kundef();
   is_kundef2();
   is_kundefn();
   inilhf();
   map_chdr_in();
   map_chdr_out();
   sac_data_read();
   sac_data_read_new();
   sac_data_swap();
   sac_header_read_new();
   sac_read();
   sac_read_header();
   sac_read_internal();
   CheckByteOrder();
   sac_byte_order();
   sac_check_lovrok();
   sac_check_npts();
   sac_data_write();
   sac_data_write1();
   sac_data_write2();
   sac_header_write();
   sac_write();
   sac_write_internal();
   sac_write_r();
   DEPRECATED();
   fstrdup();
   fstrset();
   fstrtrim();
   update_distaz();
   rsach();
   sac_check_header_version();
   sac_header_read();
   sac_header_swap();
   sacio_initialize_common();
   apcmsg();
   apcmsg2();
   apcmsgnum();
   apimsg();
   aplmsg();
   clrmsg();
   getsmsg();
   check_message_subsystem();
   encode_error();
   error();
   error_occurred();
   error_status();
   getsmsg2();
   inimsg();
   message();
   mprint();
   msg();
   out();
   processed();
   sac_error_control();
   sac_message_control();
   sac_msg_add();
   sac_warning_control();
   warning();
   sacmsg();
   sendmesg();
   setmsg();
   typmsg();
   wrtmsg();
   apfmsg();
   bell();
   bell_off();
   bell_on();
   outmsg();
   byteswap();
   cnvita();
   fill();
   ljust();
   dsum();
   extrma();
   fsum();
   kahan_sum();
   distaz();
   createvlist();
   deletev();
   deletevlist();
   getvFILEptr();
   getvvstring();
   getvvstringZ();
   token_to_line();
   upcase_dup();
   initializevars();
   inivars();
   vfilelist_free();
   putvFILEptr();
   putvvstring();
   readvfile();
   writevfile();
   bbf_to_sacvar();
   dict_free_var();
   len4();
   sac_vars_create();
   sac_vars_delete();
   sac_vars_delete_var();
   sac_vars_exists();
   sac_vars_free();
   sac_vars_get();
   sac_vars_get_int();
   sac_vars_get_internal();
   sac_vars_get_string();
   sac_vars_get_value();
   sac_vars_get_var();
   sac_vars_init();
   sac_vars_keys();
   sac_vars_put_var();
   sac_vars_read();
   sac_vars_to_bbf();
   sac_vars_write();
   setvar();
   setvar_ap();
   var_alloc();
   var_free();
   var_init();
   var_new();
   var_new_int();
   var_new_internal();
   var_new_list();
   var_new_string();
   var_new_value();
   dict_entry_alloc();
   dict_free();
   dict_get();
   dict_get_internal();
   dict_keys();
   dict_new();
   dict_new_with_length();
   dict_put();
   dict_remove();
   dict_resize();
   dict_resize_limit();
   dict_status();
   hash();
   prime_larger();
   bbf_error();
   bbf_free();
   bbf_message();
   bbf_new();
   bbf_read();
   bbf_set_header();
   bbf_set_library_use();
   bbf_set_var();
   bbf_verbose();
   bbf_write();
   decodeHeader();
   dumpHeader();
   encodeHeader();
   int2bin();
   swap();
   debug();
   fgetsp();
   read_chars();
   sscanff();
   strchr_reverse();
   strchr_reverse_isnot();
   string_alloc();
   string_append();
   string_append_int();
   string_check();
   string_check_length();
   string_compare();
   string_compare_v();
   string_compare_v_inv();
   string_copy();
   string_count();
   string_dump();
   string_dump_v();
   string_equal();
   string_equal_char();
   string_free();
   string_free_v();
   string_from_fortran();
   string_grow();
   string_insert();
   string_length();
   string_nalloc();
   string_new();
   string_pack();
   string_prepend();
   string_prepend_int();
   string_printf();
   string_printf_append();
   string_printf_append_internal();
   string_printf_prepend();
   string_printf_prepend_internal();
   string_remove();
   string_replace();
   string_string();
   string_substr();
   string_substr_char();
   string_trunc();
   strstr_escape();
   datetime_add_hms();
   datetime_alloc();
   datetime_atoi();
   datetime_atol();
   datetime_compare();
   datetime_copy();
   datetime_copy_deep();
   datetime_day_of_the_week();
   datetime_doy2ymd();
   datetime_free();
   datetime_in_span();
   datetime_init();
   datetime_merge();
   datetime_new();
   datetime_normalize();
   datetime_normalize_ymd();
   datetime_parse();
   datetime_print();
   datetime_print_date();
   datetime_printn();
   datetime_printn_date();
   datetime_set_day();
   datetime_set_doy();
   datetime_set_hour();
   datetime_set_minute();
   datetime_set_month();
   datetime_set_nanosecond();
   datetime_set_second();
   datetime_set_year();
   datetime_status();
   datetime_status_message();
   datetime_string();
   datetime_strptime();
   datetime_ymd2doy();
   day_of_the_week();
   doy();
   norm();
   year();
 return 0;
}

