
void khdr();
void sac_alloc();
void sac_comps();
void sac_copy();
void sac_extrema();
void sac_free();
void sac_hdr_init();
void sac_hdr_new();
void sac_meta_new();
void sac_new();
void powi();
void getfhv();
void getfhv_();
void getfhv__();
void sacio_char_to_keyword();
void getihv();
void getihv_();
void getihv__();
void getihv_internal();
void getkhv();
void getkhv_();
void getkhv__();
void getkhv_internal();
void hdr_len();
void getlhv();
void getlhv_();
void getlhv__();
void getnhv();
void getnhv_();
void getnhv__();
void newhdr();
void newhdr_();
void newhdr__();
void check_precision();
void rsac1();
void rsac1_();
void rsac1__();
void sac_check_time_precision();
void sac_data_read();
void sac_data_read_new();
void sac_data_swap();
void sac_header_read_new();
void sac_read();
void sac_read_header();
void sac_read_internal();
void rsac2();
void rsac2_();
void rsac2__();
void setfhv();
void setfhv_();
void setfhv__();
void setihv();
void setihv_();
void setihv__();
void setkhv();
void setkhv_();
void setkhv__();
void setlhv();
void setlhv_();
void setlhv__();
void setnhv();
void setnhv_();
void setnhv__();
void sac_check_lovrok();
void sac_check_npts();
void sac_data_write();
void sac_data_write1();
void sac_data_write2();
void sac_header_write();
void sac_write();
void sac_write_internal();
void wsac0();
void wsac0_();
void wsac0__();
void wsac1();
void wsac1_();
void wsac1__();
void wsac2();
void wsac2_();
void wsac2__();
void update_distaz();
void wsac3();
void wsac3_();
void wsac3__();
void rsach();
void sac_check_header_version();
void sac_header_read();
void sac_header_swap();
void distaz();
void sacio_message();
void sacio_message_control();
void not_used(int v);
int main() {
   not_used(0);
   return 0;
}
void
not_used(int v) {
   if (v == 0) {
       return;
   }
     khdr();
     sac_alloc();
     sac_comps();
     sac_extrema();
     sac_free();
     sac_hdr_init();
     sac_hdr_new();
     sac_meta_new();
     sac_new();
     getfhv();
     getfhv_();
     getfhv__();
     sacio_char_to_keyword();
     sacio_message();
     sacio_message_control();
     getihv();
     getihv_();
     getihv__();
     getihv_internal();
     getkhv();
     getkhv_();
     getkhv__();
     getkhv_internal();
     hdr_len();
     getlhv();
     getlhv_();
     getlhv__();
     getnhv();
     getnhv_();
     getnhv__();
     newhdr();
     newhdr_();
     newhdr__();
     check_precision();
     rsac1();
     rsac1_();
     rsac1__();
     sac_check_time_precision();
     sac_data_read();
     sac_data_read_new();
     sac_data_swap();
     sac_header_read_new();
     sac_read();
     sac_read_header();
     sac_read_internal();
     rsac2();
     rsac2_();
     rsac2__();
     setfhv();
     setfhv_();
     setfhv__();
     setihv();
     setihv_();
     setihv__();
     setkhv();
     setkhv_();
     setkhv__();
     setlhv();
     setlhv_();
     setlhv__();
     setnhv();
     setnhv_();
     setnhv__();
     sac_check_lovrok();
     sac_check_npts();
     sac_data_write();
     sac_data_write1();
     sac_data_write2();
     sac_header_write();
     sac_write();
     sac_write_internal();
     wsac0();
     wsac0_();
     wsac0__();
     wsac1();
     wsac1_();
     wsac1__();
     wsac2();
     wsac2_();
     wsac2__();
     update_distaz();
     wsac3();
     wsac3_();
     wsac3__();
     rsach();
     sac_check_header_version();
     sac_header_read();
     sac_header_swap();

     distaz();
     powi();
}
