name: Release
env:
  GITHUB_TOKEN: ${{ github.TOKEN }}
on:
  workflow_dispatch: # Trigger on manual run
  push:
    release:
    types: [published]

jobs:
  test-matrix:
    name: ${{ matrix.platform-os-name }} build
    runs-on: ${{ matrix.platform.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: macos-arm
            runs-on: macos-latest
            target: arm-apple-darwin
          - name: macos-x86_64
            runs-on: macos-13
            target: x86_64-apple-darwin
          - name: linux-x86_64
            runs-on: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - name: linux-arm
            runs-on: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: Install dependencies
        uses: amitie10g/install-package@v1
        with:
          brew: libxml2 curl libxpm libx11
          apt: libxml2-dev libxpm-dev libxmp4 libx11-dev libcurl4-openssl-dev
      - name: Create Build directory
        run: mkdir build
      - name: Configure
        working-directory: ./build
        run: ../configure --enable-editline
      - name: Compile
        working-directory: ./build
        run: make
      - name: Distributions
        working-directory: ./build
        run: make dist-binary
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          draft: true
          prerelease: true
          files: |
            License
            CHANGES
            README.md
            build/sac-*.tar.gz
