name: Updates
on:
  push:
    branches: [ "main" ]

jobs:
  test-matrix:
    name: ${{ matrix.platform-os-name }} build
    runs-on: ${{ matrix.platform.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os-name: macOS-aarch64
            runs-on: macOS-latest
            target: aarch64-apple.darwin
          - os-name: macOS-x86_64
            runs-on: macOS-latest
            target: x86_64-apple.darwin
          - os-name: Linux-x86_64
            runs-on: ubuntu-latest
            target: x86_64-unknown-linux-musl
          - os-name: Linux-i686
            runs-on: ubuntu-latest
            target: i686-unknown-linux-musl
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: Install dependencies
        uses: amitie10g/install-package@v1
        with:
          brew: libxml2 curl libxpm libx11
          apt: libxml2-dev libxpm-dev libxmp4 libx11-dev libcurl4-openssl-dev
      - name: Create Build directory
        run: mkdir build
      - name: Configure
        working-directory: ./build
        run: ../configure --enable-editline
      - name: Compile
        working-directory: ./build
        run: make
      - name: Distributions
        working-directory: ./build
        run: make dist-binary
      - name: Done
        run: echo "Status ${{ job.status }}"
      - uses: actions/download-artifact@v4
        with:
          pattern: build/sac-*tar.gz

